# Welcome to Suna config file

# Site settings
title: Youth Movement for employment and violence free africa
email: yomeva2017@gmail.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

# Other site wide variables



# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM


# Sass Settings
sass:
  sass_dir: assets/styles/_scss
  style: compressed


# Exclude the following from the Jekyll build process.
exclude:
  - Gemfile
  - Gemfile.lock



# Collections
collections:
  whatwedocollection:
     output: true;

  executivecollection:
     output: true;
  projectcollection:
      
   

